# Generated by Django 3.1.5 on 2021-01-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210128_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mainphoto',
            new_name='images',
        ),
    ]
